# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Hear-Yinz' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Hear-Yinz
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'

  target 'Hear-YinzTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Hear-YinzUITests' do
    # Pods for testing
  end

end
